CREATE DATABASE info;


CREATE TABLE employee(
ID INT PRIMARY KEY IDENTITY(1,1),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50),
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
NUMBER VARCHAR(50)
);

SELECT * from employee;

